db:
  mysql:
    host: mysqldb
    port: 3306
    name: testdb
    user: root
    pass: 123456aA

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/testdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: 123456aA
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 3000
      idleTimeout: 10000
      maxLifetime: 30000
  jackson:
    serialization:
      indent_output: true